service: artwilioapi

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sendmessage:
    handler: handler.send
    events:
    - http:
        path: send
        method: post
        cors: true
