service: artwilioapi

provider:
  name: aws
  runtime: nodejs6.10

functions:
  sendmessage:
    handler: handler.send
    events:
    - http:
        path: send
        method: post
        cors: true
  postarmodel:
    handler: handler.postarmodel
    events:
    - http:
        path: arproducts
        method: post
        cors: true
  postarmodelinfo:
    handler: handler.postarmodelinfo
    events:
    - http:
        path: arproductinfo
        method: post
        cors: true
  getarmodelinfo:
    handler: handler.getarmodelinfo
    events:
    - http:
        path: arproductinfo/{productid}
        method: get
        cors: true
